### ISSUE TITLE
Version v1.2.3 is generating errors

### ISSUE THREAD

**Issue by miguelaferreira** [wow-actions/delete-stale-releases#3]
The action execution is failing, and I get the following log line and then a big dump of JavaScript code.
```
/home/runner/work/_actions/wow-actions/delete-stale-releases/v1.2.3/dist/index.js.cache.js:14
```

### Expected Behavior

The action executes and deletes the releases according to configuration.

### Current Behavior

The execution fails, the log line mentioned above is printed together with a dump of JavaScript code.

### Steps To Reproduce

1. Create a workflow that runs on closed PRs
2. Add the following step to a job on that workflow (where `'*rc*'` is a regex to match specific releases).
   ```
       - name: Delete GitHub release candidates
      id: delete-github
      uses: wow-actions/delete-stale-releases@v1.2.3
      with:
        key: name
        include: '*rc*'
        include_prerelease: true
        include_draft: true
        delete_tags: true
   ```
3. Open and close a PR
4. The workflow fails

<details><summary>Error Message & Stack Trace</summary>

Log file: [action-execution-log.txt](https://github.com/wow-actions/delete-stale-releases/files/10054567/1_delete-release-candidates.1.txt)

</details>

### Additional Context

I'm trying to run the action. It used to work before and it stopped working at some point.

### Your Environment

Action is running on GitHub actions `ubuntu-latest`.
In my environment, release `v1.2.1` works correctly and the issue reported here starts to happen as of release `v1.2.2`.
